name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:  # Cambiamos el nombre del job para claridad

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker (opcional)
      # Si tu repositorio privado requiere autenticación para Docker Hub
      # agrega este paso para iniciar sesión. 
      # Ten en cuenta la seguridad al almacenar credenciales en GitHub Actions.
      # Busca en la documentación de Actions sobre autenticación de Docker.
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portafolioimage:$(date +%s)
    - name: Deploy to GitHub Pages (con Docker)
      uses: crazymax/docker-action@v2  # Acción para ejecutar comandos Docker
      with:
        image: portafolioimage:$(date +%s)  # Imagen construida previamente
        args: ["--rm", "-p", "80:80"]  # Argumentos para ejecutar Apache
        services: ["httpd"]           # Servicio a ejecutar desde la imagen
