name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:  # Cambiamos el nombre del job para claridad

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portafolioimage:$(date +%s)
    - name: Deploy to GitHub Pages (con Docker)
      uses: crazymax/docker-action@v2
      with:
        image: portafolioimage:$(date +%s)
        args: "--rm -p 80:80"
        services: "httpd"

